version: "3.1"
services:
   amsterdam-subsidies:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/opt/as
    networks:
      - as
    restart: always
networks:
  as:
